#ifndef QRD_DEMO_CONFIG_H
#define QRD_DEMO_CONFIG_H

#define MAX_FILES 255
#define MAX_FILENAME_LENGTH 127
#define MAX_DECODED_SYMBOLS 255
#define MAX_MESSAGE_LEN 1023
#define DIR_PATH_IMAGES "../../images-test/"
#define PNG_BYTES_TO_CHECK 4

#define SHOW_LIST_PASSED 0
#define SHOW_LIST_UNPASSED 0
#define SHOW_RESULT_FLAGS 0
#define USE_TICKS_INSTEAD_MILLISECONDS 0



#endif /* QRD_DEMO_CONFIG_H */
